---
 - name: add the firewall rule
   firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
 - name: relod firewall configration for new rule
   systemd:
        name: firewalld
        state: reloaded
 - name: copy the file from apache directory
   copy:
        src: files/index.html
        dest: /var/www/html/

